version: "2"
plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
- "**/node_modules/"
- "**/vendor/"
- "**/*.d.ts"